name: Docker Actions
on: [push]
jobs:
  my_job: 
    runs-on: ubuntu-latest
    container: rocker/verse
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |-
          installGithub.r --update FALSE clauswilke/ggtext
          install2.r fs
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render mansucript
        run: |-
          Rscript -e "lapply(fs::dir_ls('manuscript', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"

## remarkably(?), we can use the standard checkout action, actions/checkout@v1
## even inside this Docker container.

